<a href="https://colab.research.google.com/github/SyedT1/Data-Mining-CSC417/blob/main/Lectures/lect_2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import numpy as np
path = 'https://raw.githubusercontent.com/SyedT1/Data-Mining-CSC417/main/Week%201/datasets/iris.data'
cols = ['sepal_len','sepal_wid','petal_len','petal_wid','name']
df = pd.read_csv(path,names = cols)
print(df)
species = [i for i in set(df['name'])]
species = species[::-1]
print(species)


     sepal_len  sepal_wid  petal_len  petal_wid            name
0          5.1        3.5        1.4        0.2     Iris-setosa
1          4.9        3.0        1.4        0.2     Iris-setosa
2          4.7        3.2        1.3        0.2     Iris-setosa
3          4.6        3.1        1.5        0.2     Iris-setosa
4          5.0        3.6        1.4        0.2     Iris-setosa
..         ...        ...        ...        ...             ...
145        6.7        3.0        5.2        2.3  Iris-virginica
146        6.3        2.5        5.0        1.9  Iris-virginica
147        6.5        3.0        5.2        2.0  Iris-virginica
148        6.2        3.4        5.4        2.3  Iris-virginica
149        5.9        3.0        5.1        1.8  Iris-virginica

[150 rows x 5 columns]
['Iris-virginica', 'Iris-setosa', 'Iris-versicolor']


In [26]:

a = np.array([list(i) for i in zip(df['sepal_len'].to_numpy(),df['sepal_wid'].to_numpy(),df['petal_len'].to_numpy(),df['petal_wid'].to_numpy())])
a

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

# Calculating mean of the matrix
 $\hat{\mu} = \frac{1}{n} \sum_{i=1}^n x_i$

In [66]:
sum = np.zeros(a.shape[1])
sum

array([0., 0., 0., 0.])

In [67]:
for row in a:
  sum += row
mean = sum / a.shape[0]

In [68]:
mean

array([5.84333333, 3.054     , 3.75866667, 1.19866667])

In [73]:
x = np.array([df['sepal_len'].mean(),df['sepal_wid'].mean(),df['petal_len'].mean(),df['petal_wid'].mean()])
x

array([5.84333333, 3.054     , 3.75866667, 1.19866667])

# Calculating covariance of the matrix